// global-actions
export const CHECK_DEVICE_SIZE = 'CHECK_DEVICE_SIZE'
export const LOADING_STATE_CHANGE = 'LOADING_STATE_CHANGE'
export const TOGGLE_MENU_DROPDOWN = 'TOGGLE_MENU_DROPDOWN'

// user-actions
export const CHECK_FOR_USER_SUCCESS = 'CHECK_FOR_USER_SUCCESS'
export const CHECK_FOR_USER_FAILURE = 'CHECK_FOR_USER_FAILURE'

export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS'
export const USER_SIGN_UP_FAILURE = 'USER_SIGN_UP_FAILURE'

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'

export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE'

export const SEND_EMAIL_VERIFICATION_SUCCESS = 'SEND_EMAIL_VERIFICATION_SUCCESS'
export const SEND_EMAIL_VERIFICATION_FAILURE = 'SEND_EMAIL_VERIFICATION_FAILURE'

export const VERIFY_PASSWORD_RESET_CODE_SUCCESS = 'VERIFY_PASSWORD_RESET_CODE_SUCCESS'
export const VERIFY_PASSWORD_RESET_CODE_FAILURE = 'VERIFY_PASSWORD_RESET_CODE_FAILURE'

export const CONFIRM_PASSWORD_RESET_SUCCESS = 'CONFIRM_PASSWORD_RESET_SUCCESS'
export const CONFIRM_PASSWORD_RESET_FAILURE = 'CONFIRM_PASSWORD_RESET_FAILURE'

export const SEND_PASSWORD_RESET_EMAIL_SUCCESS = 'SEND_PASSWORD_RESET_EMAIL_SUCCESS'
export const SEND_PASSWORD_RESET_EMAIL_FAILURE = 'SEND_PASSWORD_RESET_EMAIL_FAILURE'

export const USER_UPDATE_PASSWORD_SUCCESS = 'USER_UPDATE_PASSWORD_SUCCESS'
export const USER_UPDATE_PASSWORD_FAILURE = 'USER_UPDATE_PASSWORD_FAILURE'

export const UPLOAD_PROFILE_PICTURE_SUCCESS = 'UPLOAD_PROFILE_PICTURE_SUCCESS'
export const UPLOAD_PROFILE_PICTURE_FAILURE = 'UPLOAD_PROFILE_PICTURE_FAILURE'

export const SANITIZE_USER_STATE = 'SANITIZE_USER_STATE'
export const SANITIZE_USER_ERROR_STATE = 'SANITIZE_USER_ERROR_STATE'
