// global-actions
export const CHECK_DEVICE_SIZE = 'CHECK_DEVICE_SIZE'
export const LOADING_STATE_CHANGE = 'LOADING_STATE_CHANGE'
export const TOGGLE_MENU_DROPDOWN = 'TOGGLE_MENU_DROPDOWN'

// user-actions
export const CHECK_FOR_USER_SUCCESS = 'CHECK_FOR_USER_SUCCESS'
export const CHECK_FOR_USER_FAILURE = 'CHECK_FOR_USER_FAILURE'

export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS'
export const USER_SIGN_UP_FAILURE = 'USER_SIGN_UP_FAILURE'

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'

export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE'

export const CLEAR_USER_ERROR_MESSAGE = 'CLEAR_USER_ERROR_MESSAGE'
